#!/usr/bin/env python3
"""Generate assets.c for the port from the original ski32.exe.

    tools/gen_assets.py etc/original-binaries/ski32.exe build/assets.c

Extracts, so nothing is transcribed by hand:
  - the 89 bitmap resources, as complete .bmp files (file header prepended),
    with their width/height
  - the string table
  - the game's data tables from .rdata (state->sprite, initial states, turn
    table, motion tables, landing table)

The declarations live in src/assets.h.
"""
import struct
import sys

import pefile

IMAGE_BASE = 0x400000
NUM_SPRITES = 90  # resource ids 1..89; slot 0 is empty

# .rdata tables: (C name, virtual address, struct format, count)
TABLES = {
    "stateSprite": (0x40A1AC, "<H", 64),
    "initialState": (0x40A22C, "<i", 11),
    "turnTable": (0x40A258, "<2i", 22),
    "playerMotion": (0x40A308, "<6hi", 22),
    "landingState": (0x40A468, "<i", 9),
    "skierMotion": (0x40A490, "<6hi", 5),
    "snowboarderMotion": (0x40A4E0, "<6hi", 8),
}

# Spot checks from the analysis (analysis/ski32/NOTES.md).
EXPECTED_SIZES = {1: (16, 32), 12: (32, 32), 27: (64, 32), 53: (93, 57), 64: (24, 64), 89: (28, 32)}


def read_table(pe, va, fmt, count):
    size = struct.calcsize(fmt)
    data = pe.get_data(va - IMAGE_BASE, size * count)
    return [struct.unpack_from(fmt, data, i * size) for i in range(count)]


def resources(pe, type_id):
    for entry in pe.DIRECTORY_ENTRY_RESOURCE.entries:
        if entry.id == type_id:
            for name in entry.directory.entries:
                lang = name.directory.entries[0]
                rva, size = lang.data.struct.OffsetToData, lang.data.struct.Size
                yield name.id, pe.get_data(rva, size)


def bitmap_file(dib):
    """Prepend a BITMAPFILEHEADER to a resource DIB."""
    bi_size, width, height, _planes, bpp = struct.unpack_from("<IiiHH", dib)
    clr_used = struct.unpack_from("<I", dib, 32)[0]
    colors = clr_used or (1 << bpp if bpp <= 8 else 0)
    offset = 14 + bi_size + 4 * colors
    header = struct.pack("<2sIHHI", b"BM", 14 + len(dib), 0, 0, offset)
    return header + dib, width, abs(height)


def c_bytes(data, indent="    "):
    lines = []
    for i in range(0, len(data), 16):
        lines.append(indent + ",".join(str(b) for b in data[i:i + 16]) + ",")
    return "\n".join(lines)


def c_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    exe, out = sys.argv[1], sys.argv[2]
    pe = pefile.PE(exe)

    bitmaps = {}
    for rid, dib in resources(pe, pefile.RESOURCE_TYPE["RT_BITMAP"]):
        bitmaps[rid] = bitmap_file(dib)
    assert sorted(bitmaps) == list(range(1, NUM_SPRITES)), sorted(bitmaps)
    for rid, size in EXPECTED_SIZES.items():
        assert bitmaps[rid][1:] == size, (rid, bitmaps[rid][1:], size)

    strings = {}
    for block, data in resources(pe, pefile.RESOURCE_TYPE["RT_STRING"]):
        off = 0
        for i in range(16):
            n = struct.unpack_from("<H", data, off)[0]
            off += 2
            if n:
                strings[(block - 1) * 16 + i] = data[off:off + 2 * n].decode("utf-16le")
            off += 2 * n
    num_strings = max(strings) + 1

    tables = {name: read_table(pe, *spec) for name, spec in TABLES.items()}
    for name, base in (("playerMotion", 0), ("skierMotion", 22), ("snowboarderMotion", 31)):
        for i, row in enumerate(tables[name]):
            assert row[6] == base + i, (name, i, row)

    o = []
    o.append("/* Generated by tools/gen_assets.py from ski32.exe. Do not edit. */")
    o.append('#include "assets.h"')
    o.append("")
    for rid in range(1, NUM_SPRITES):
        o.append(f"static const unsigned char bmp_{rid}[] = {{")
        o.append(c_bytes(bitmaps[rid][0]))
        o.append("};")
    o.append("")
    o.append("const SkiBitmap ski_bitmaps[SKI_NUM_SPRITES] = {")
    o.append("    {0, 0, 0, 0},")
    for rid in range(1, NUM_SPRITES):
        data, w, h = bitmaps[rid]
        o.append(f"    {{{w}, {h}, bmp_{rid}, sizeof bmp_{rid}}},")
    o.append("};")
    o.append("")
    o.append(f"const char *const ski_strings[{num_strings}] = {{")
    for i in range(num_strings):
        o.append(f"    {c_string(strings.get(i, ''))},")
    o.append("};")
    o.append("")

    def scalar_table(ctype, name):
        vals = ", ".join(str(r[0]) for r in tables[name])
        o.append(f"const {ctype} ski_{name}[{len(tables[name])}] = {{{vals}}};")

    scalar_table("uint16_t", "stateSprite")
    scalar_table("int32_t", "initialState")
    scalar_table("int32_t", "landingState")
    rows = ", ".join(f"{{{a}, {b}}}" for a, b in tables["turnTable"])
    o.append(f"const int32_t ski_turnTable[22][2] = {{{rows}}};")
    for name in ("playerMotion", "skierMotion", "snowboarderMotion"):
        o.append(f"const SkiMotion ski_{name}[{len(tables[name])}] = {{")
        for r in tables[name]:
            o.append("    {" + ", ".join(str(v) for v in r) + "},")
        o.append("};")

    with open(out, "w") as f:
        f.write("\n".join(o) + "\n")
    print(f"{out}: {len(bitmaps)} bitmaps, {len(strings)} strings, {len(tables)} tables")


if __name__ == "__main__":
    main()
